### ISSUE TITLE
Version/Capabilities of Chromium in Readme

### ISSUE THREAD

**Issue by carlcraig** [csegames/cu-ui#10]
Hi,

It could be nice to have some information in the readme regarding the version of webkit/chromium running the UI. Possibly some information on its capabilities *(not sure if all chromium features would be enabled in the UI?)*

There are lots of interesting features in some of the newer versions, which could be very useful to the UI *(thinking of things like `Object.observe()`, and some of the new css3 features).*

**Comment by codecorsair** [comment]
I've added the version to the readme.  Features / issues with CEF / Chromium are not something I feel would work well in a readme, however they may be useful notes elsewhere.

**Comment by carlcraig** [comment]
:+1: is good, will allow us to lookup capabilities based on chrome version.

Only thing that might be useful, it a list of things enabled/disabled by CEF, like localStorage, file API etc
